### ISSUE TITLE
Negative values of SurpriseVertexPartition quality function

### ISSUE THREAD

**Issue by sharpsy** [vtraag/leidenalg#137]
When using the SurpriseVertexPartition, values of the quality function can be negative. Although I have seen this happen only when evaluating surprise *without* optimization (ie. by setting the initial_membership of nodes and immediately evaluating quality).
In my understanding, surprise should always be non-negative. From the definition of quality function, a product of number of edges and KL divergence, both factors are non-negative. In the implementation of this quality function (https://github.com/vtraag/libleidenalg/blob/main/src/SurpriseVertexPartition.cpp#L138C16-L138C19), a KLL function is used that multiplies the result by `-1` if the fraction of internal edges is less than expected value of this fraction.

In my experiments, just after initialization partitions that received smaller surprise (or maximum of absolute value of surprise) were qualitatively better. Once optimized and surprise reached positive values, perceived quality of partitions decreased. I have checked this by visualizing such graph (separation between communities is decreased) and confirmed by evaluating data with known cluster assignments - NMI evaluation metric significantly decreases with optimization.

It appears that this minus sign in quality function implementation can therefore force de-optimization of proper community separation.

**Comment by vtraag** [comment]
Indeed, `KLL` multiplies the original Kullback-Leibler divergence $D(q, p)$  by $-1$ if $q < p$, where $p$ is the expected internal density and $q$ the actual internal density of the partition. The multiplication with $-1$ is intentional. Let me briefly explain why. 

For $q = p$ the Kullback-Leibler divergence $D(q, p) = 0$ and $D > 0$ whenever $q \neq p$. However, we are typically interested in the regime where $q > p$, not in the regime where $q < p$. In the regime where $q > p$, we find clusters that have a relatively higher internal connectivity, while in the regime where $q < p$ we find clusters with relatively lower internal connectivity. Once the algorithm is in a regime where $q < p$, it tends to improve the partition by making $q$ even lower, instead of $q$ even higher. By multiplying it with $-1$ in the regime where $q < p$, we essentially force the algorithm towards the regime where $q > p$.

Of course, it might be that you are interested in a multipartite/disassortative structure (with relatively few internal links) instead of a clustering/assortative structure (with relatively many internal links). In principle, you could create a new partition type that does exactly this. See https://leidenalg.readthedocs.io/en/stable/implement.html for more details now how to implement your own partition type.

Perhaps you are not even interested in disassortative/assortative structures, but in more general types of block structures. If so, you could for example consider using stochastic block models. See for example https://graph-tool.skewed.de/static/doc/demos/inference/inference.html for more info.

**Comment by sharpsy** [comment]
I believe I see your point with the reasoning on multiplication with -1. I was using several partition quality functions to evaluate known cluster assignments - and was taken aback with negative values from SurpriseVertexPartition.

Thank you for the very fast response and thorough answer.
