### ISSUE TITLE
API documentation not rendering

### ISSUE THREAD

**Issue by Gilquin** [vtraag/leidenalg#143]
Hello,

The [reference page](https://leidenalg.readthedocs.io/en/latest/reference.html) is not rendering the API documentation since a few weeks. I don't know if it is intended or not.

**Comment by vtraag** [comment]
Ah, thanks for noting! I hadn't yet seen this myself. I'll take a closer look.

**Comment by vtraag** [comment]
The [latest documentation](https://leidenalg.readthedocs.io/en/latest/) now builds correctly. The "stable" documentation will only be updated when I make a new release, which I in principle can do shortly. I'll leave the issue open.

More as a note to myself: at the moment, the build system at read the docs works directly with the provided `igraph` and `libleidenalg` packages from `conda-forge`. The original problem was that the C dependencies were not found by the documentation build system, because they were in different paths. Installing the dependencies in the correct `conda` library didn't seem to work, so for now, we're limited to released versions that are already available from `conda-forge` to build the documentation.

**Comment by vtraag** [comment]
I just made a new release (0.10.1) so the "stable" documentation is now also correct again.
