### ISSUE TITLE
Error while using Leiden algorithm in Seurat

### ISSUE THREAD

**Issue by Panzer-vor-08** [vtraag/leidenalg#177]
I was using FindClusters function in Seurat v5 before I met this error:

> Error in unlist(object) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:537

It only happens when algorithm is set to 4 (i.e. using Leidenalg). Does anyone else met this issue?

**Comment by vtraag** [comment]
Sorry, but I know almost nothing about Seurat, so it's probably better to open an issue https://github.com/satijalab/seurat/issues. If there is a specific issue with `leidenalg`, and can provide a reproducible example that does not depend on Seurat, I can look into it. Without it, it might very well be that the problem is actually located in Seurat, not in `leidenalg`.
