### ISSUE TITLE
Error when running leidenalg on more than 50k samples

### ISSUE THREAD

**Issue by kaizen89** [vtraag/leidenalg#22]
Hello,
I am using Seurat package to analyse single cell data with more than 50k cells. 
When I run the clustering on low number of cells, it works fine, however when I run it on the whole data, I get:
```
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
> traceback()
7: asMethod(object)
6: as(object, "matrix")
5: RunLeiden(object = object, method = method, partition.type = "RBConfigurationVertexPartition", 
       initial.membership = initial.membership, weights = weights, 
       node.sizes = node.sizes, resolution.parameter = r, random.seed = random.seed, 
       n.iter = n.iter)
4: FindClusters.default(object = object[[graph.name]], modularity.fxn = modularity.fxn, 
       initial.membership = initial.membership, weights = weights, 
       node.sizes = node.sizes, resolution = resolution, algorithm = algorithm, 
       n.start = n.start, n.iter = n.iter, random.seed = random.seed, 
       group.singletons = group.singletons, temp.file.location = temp.file.location, 
       edge.file.name = edge.file.name, verbose = verbose, ...)
3: FindClusters(object = object[[graph.name]], modularity.fxn = modularity.fxn, 
       initial.membership = initial.membership, weights = weights, 
       node.sizes = node.sizes, resolution = resolution, algorithm = algorithm, 
       n.start = n.start, n.iter = n.iter, random.seed = random.seed, 
       group.singletons = group.singletons, temp.file.location = temp.file.location, 
       edge.file.name = edge.file.name, verbose = verbose, ...)
2: FindClusters.Seurat(merge, resolution = 0.5, algorithm = 4)
1: FindClusters(merge, resolution = 0.5, algorithm = 4)
```
Algorithm=4 (4 is for leidenalg).
I guess this error is linked to leidenalg and not to Seurat.
Any help?
Thanks

**Comment by vtraag** [comment]
I think @TomKellyGenetics can tell you more about this. The file `cholmod_dense.c` is not used in the `leidenalg` package itself, so presumably it relates to some preprocessing that is done by `seurat` before calling `leidenalg`.

**Comment by TomKellyGenetics** [comment]
Which version of Seurat are you using? Please try the development version. Recent updates have been merged to handle large datasets. See discussions here for details:

https://github.com/satijalab/seurat/issues/1645
https://github.com/satijalab/seurat/pull/1858
https://github.com/satijalab/seurat/issues/2168
https://github.com/satijalab/seurat/pull/2169

 For Issues or changes to R versions of Leiden please refer to the dedicated repositories for the "leiden" and "Seurat" CRAN packages. In this case I think the issue is actually with the Seurat interface called when running `FindClusters`. I think similar issues have already been reported and the latest version should not have this problem. Try installing the development version (`devtools::install_github("satijalab/Seurat", ref = "develop"`) and report it if your still have problems.

https://github.com/satijalab/seurat
https://github.com/TomKellyGenetics/leiden

Please note that the "leiden" package uses reticulate to call the Python implementation of "leidenalg". Several implementations calling C directly from R (which will have improved performance on large datasets) are in development such as:

https://github.com/cole-trapnell-lab/leidenbase
https://github.com/igraph/rigraph/issues/346

**Comment by vtraag** [comment]
In the near future, the Leiden algorithm will be implemented in `igraph` itself. The PR for the implementation in the C core is already submitted https://github.com/igraph/igraph/pull/1259

**Comment by kaizen89** [comment]
Thanks Tom for the answer. Unfortunately, I am still not able to run leiden alg on a relatively large dataset, more than 15 min after running FindClusters and still nothing. I have installed the develop versions of Seurat and leiden. The FindClusters works well with a small dataset but not with a larger one.
I tried to run it directly on the SNN graph but couldnt. (error related to my first comment)
```
adjacency_matrix <- as.matrix(merged@graphs$RNA_snn)
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
```

**Comment by TomKellyGenetics** [comment]
@kaizen89 I understand your issue but I think it's very similar in nature to satijalab/seurat#1645. Please see the responses there. Try running `Seurat::FindClusters` with `method="igraph"` to avoid running `as.matrix` on a large sparse matrix or using a server with sufficient memory available. If you still have issues, please file a new one to the relevant repository for Seurat or the R `leiden` package. 

As discussed elsewhere, implementations calling C from R directly will have improved performance. I would recommend the `igraph` version once it becomes available in R (r-igraph) or Python (python-igraph).

**Comment by kaizen89** [comment]
Ok thanks @TomKellyGenetics. I will file a new issue as I still have the same problem when setting method="igraph", FindClusters runs without errors but nothing happens for several minutes and it doesn't seem to be a problem with memory. 
I have already installed python-igraph but was getting the error: Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105.
Thanks again.

**Comment by TomKellyGenetics** [comment]
This issue is not caused by leiden implementations in R or Python but in preprocessing steps by Seurat. Running `as.matrix(merge["RNA_snn"])` is returning an error from a dependency in C on the `Matrix` package for sparse matrices. This should only happen for `method="matrix"` as the igraph does not cast to a dense matrix (satijalab/seurat#1645). 

https://github.com/satijalab/seurat/blob/fc4a4f5203227832477a576bfe01bc6efeb23f51/R/clustering.R#L718

If the issue persists please submit an issue with the traceback for `method="igraph"` in using the development version of Seurat to the Seurat repository. I'm not a core developer of Seurat so please tag me and reference this issue so they are aware of the situation.

**Comment by kaizen89** [comment]
Will do, thanks @TomKellyGenetics
