### ISSUE TITLE
What is the best default method to cluster kNN graphs while having control over resolution?

### ISSUE THREAD

**Issue by dkobak** [vtraag/leidenalg#26]
The library supports a variety of methods (modularity, CPM, etc.) but I couldn't find any guidance as to what should be a reasonable default. The Scientific Reports paper only describes modularity and CPM, but the package implements many further methods. Is there a beginner's guide to how to choose one of them?

Here https://leidenalg.readthedocs.io/en/latest/intro.html you use `la.ModularityVertexPartition` for the first example. However, if I try to pass `resolution_parameter`, I get an error message. Is there any way to use resolution with modularity?

The same documentation page shows how to use `la.CPMVertexPartition` with specfying resolution. But I noticed that `scanpy` implements `leidenalg` with `la.RBConfigurationVertexPartition` by default. This also allows to specify resolution. How can I choose between those, and other available methods?

**Comment by vtraag** [comment]
The `la.RBConfigurationVertexPartition` is modularity with resolution parameter. The only other minor difference with `la.ModularityVertexPartition` is that `la.ModularityVertexPartition.quality()` is normalised with the number of links (or total weight), while `la.RBConfigurationVertexPartition.quality()` is unnormalised. This is a completely trivial difference of course, but some people were confused why some quality functions did not correspond exactly to the quality functions as defined in the literature.

Personally, I favour CPM, because it does not suffer from the resolution-limit (see http://arxiv.org/abs/1104.3083). I think it also makes sense in the context of similarities. The resolution parameter of CPM can then be understood as the desirable average similarity between nodes within communities. For example, if you use a resolution of 0.9, nodes in the same community will have an average similarity of at least 0.9 with the rest of its community, and a similarity with the rest of the network that is at most 0.9. There is also a nice connection with a layout methodology (see https://arxiv.org/abs/1006.1032). It seems that most analyses still use modularity however (with resolution parameter, so `la.RBConfigurationVertexPartition`).
