### ISSUE TITLE
How to do bipartite community detection

### ISSUE THREAD

**Issue by PCK1992** [vtraag/leidenalg#27]
Your examples are great for regular community detection but unfortunately, I can't really wrap my head around how to do the same for bipartite networks. Could you perhaps give a working example (maybe in the documentation) how to use the package to retrieve lists that group nodes into communities taking the bipartite structure into account? That would be great!

**Comment by vtraag** [comment]
The documentation on detecting communities in bipartite graphs is here: https://leidenalg.readthedocs.io/en/latest/multiplex.html#bipartite. Is there anything specific about the documentation that is unclear?

There was a bug https://github.com/vtraag/leidenalg/issues/6 which is fixed in the`master' branch, but this is not yet released.
