### ISSUE TITLE
'Graph' object has no attribute 'vcount'

### ISSUE THREAD

**Issue by SruthiHarish** [vtraag/leidenalg#58]
Hai,
 I have tried Leiden package. When running it with the famous 'karate club' network, it produced an error like ''Graph' object has no attribute 'vcount''... What will be the reason?????

import leidenalg
import igraph as ig
import networkx as nx

G = nx.karate_club_graph()
part = leidenalg.find_partition(G, leidenalg.ModularityVertexPartition)

**Comment by vtraag** [comment]
The object `G` is a `networkx` object, not an `igraph` object. In the most recent versions of `igraph`, you can obtain an `igraph` object using [`from_networkx`](https://igraph.org/python/doc/igraph.Graph-class.html#from_networkx):  `G2 = igraph.Graph.from_networkx(G)`. You can then apply `leidenalg.find_partition` to `G2` instead of `G`.

**Comment by SruthiHarish** [comment]
Thank you... solved...
