### ISSUE TITLE
specific number of nodes in a cluster

### ISSUE THREAD

**Issue by Angela446-lgtm** [vtraag/leidenalg#96]
Is it possible to make  clusters with  specific number of nodes? I would like to define the number of nodes in each cluster.

**Comment by vtraag** [comment]
Hi @Angela446-lgtm, sorry, no this is not possible at the moment. There are two possibly related issues about fixing the number of clusters (#89) and enforcing a minimum community size (#53), perhaps these would also be relevant to your problem? If your problem is different, could you please elaborate? If not, it would probably be better to close this issue and move the conversation to the relevant other open issues.
